# instagram-frontend/docker-compose.yml
version: '3.8'

services:
  instagram-frontend:
    build:
      context: .
    container_name: instagram-frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - instagram-network

networks:
  instagram-network:
    external: true
