apiVersion: apps/v1
kind: Deployment
metadata:
  name: instagram-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: instagram-frontend
  template:
    metadata:
      labels:
        app: instagram-frontend
    spec:
      containers:
        - name: frontend
          image: idealclone/instagram-frontend:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: frontend-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: instagram-frontend-service
spec:
  selector:
    app: instagram-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
