import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/components/common/Sidebar";
import { cls } from "@/utils/common";
import { ToastContainer } from "react-toastify";

import "./globals.css";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cls(inter.className, "flex gap-4")}>
        <Sidebar />
        <main className={"flex-1"}>{children}</main>
        <ToastContainer position={"bottom-left"} />
      </body>
    </html>
  );
}
