name: Frontend CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: idealclone/instagram-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          build-args: |
            BACKEND_URL=${{ secrets.BACKEND_URL }}
            NEXT_SHARP_PATH=${{ secrets.NEXT_SHARP_PATH }}

      - name: Create .env file
        run: |
          cat <<EOF > .env
          NEXT_PUBLIC_BACKEND_URL=${{ secrets.BACKEND_URL }}
          NEXT_SHARP_PATH=${{ secrets.NEXT_SHARP_PATH }}
          EOF

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Set up Kubeconfig
        run: doctl kubernetes cluster kubeconfig save e204b213-4401-40bb-8ab4-2fc9f63fdcaf

      - name: Apply frontend deployment to K8s
        run: kubectl apply -f frontend-deployment.yaml
